In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Matrices

In [3]:
#create a vector
from numpy import array
v=array([1,2,3])
print(v)

#vector arithmetic
a=array([1,2,3])
print('a: ',a)
b=array([1,2,3])
print('b: ',b)
c=a+b
print('a+b: ',c)
d=array([0.1,0.5,0.9])
print('d: ',d)
e=a-d
print('a-d: ',e)
f=d*b
print('d*b',f)
g=d/b
print('d/b',g)


[1 2 3]
a:  [1 2 3]
b:  [1 2 3]
a+b:  [2 4 6]
d:  [0.1 0.5 0.9]
a-d:  [0.9 1.5 2.1]
d*b [0.1 1.  2.7]
d/b [0.1  0.25 0.3 ]


**vector dot product**



c=a.b
c=(a1*b1+a2*b2+a3*b3)

In [4]:
a=array([1,2,3])
b=array([1,2,3])
print(a)
print(b)
c=a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


**vector-scalar multiplication**

c=s x v


c=(s*v1,s*v2,s*v3)

In [5]:
a=array([1,2,3])
s=0.5
c=s*a
print(c)

[0.5 1.  1.5]


## Vector Norms

In [6]:
#vector L1 norm
from numpy import array
from numpy.linalg import norm
a=array([1,2,3])
print(a)
l1=norm(a,1)
print('norm l1: ',l1)

#vector L2 norm
l2=norm(a)
print('norml2: ',l2)

from math import inf
#vector max norm
maxnorm=norm(a,inf)
print('maxnorm: ',maxnorm)

[1 2 3]
norm l1:  6.0
norml2:  3.7416573867739413
maxnorm:  3.0


##Matrices and Matrix Artihmetic

In [7]:
#Create matrix
from numpy import array
A=array([[1,2,3],[4,5,6]])
print(A)
#matrix addition
B=array([[1,2,3],[4,5,6]])
C=A+B
print('C:   ',C)

#matrix subtraction
D=array([[0.5,0.5,0.5],[0.5,0.5,0.5]])
E=A-D
print(D)
print('A-D:  ',E)

[[1 2 3]
 [4 5 6]]
C:    [[ 2  4  6]
 [ 8 10 12]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
A-D:   [[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


**hadamard product(matrix product)**

C = A ◦ B



aynı satır ve sütun koordinatına sahip noktalar çarpılır sonuç matrisinin yine aynı satır sütununa yazılır


In [8]:
a=array([[1,2,3],[4,5,6]])
b=array([[1,2,3],[4,5,6]])
#multiply matrices
c=a*b
print(a)
print(c)
d=a/b
print(d)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


**matrix multiplication**

C=A.B
C(m,k)=A(m,n).B(n,k)
columns' A is equal rows' B
A 3x2 ve B 2x2 olsun
Anın 1. satırı bnin 1.sütunu ile çarpılıp toplanır Cnin ilk elemanı olur.

In [9]:
A=array([[1,2],
         [3,4],
         [5,6]])

B=array([[1,2],
         [3,4]])
#multiply matrices
C=A.dot(B)
print(C)
#multiply matrices with @operator
D=A@B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


In [10]:
#C=AB matrix-vector mulptiplication
A=array([[1,2],
         [3,4],
         [5,6]])
B=array([0.5,0.5])
C=A.dot(B)
#C=Ab matrix-scalar multiplication
b=0.5
D=A*b
print(C)
print(D)

[1.5 3.5 5.5]
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## **Matrix Types**

> Square Matrix

> Symmetric Matrix

> Triangular Matrix

> Diagonal Matrix

> Identity Matrix

> Orthogonal Matrix













**square matrix**

 rows number=columns number

 **Symmetric matrix**

 M = M(transpose)  Mi,j=Mj,i

 **Triangular matrix**

 it may be lower or upper matrix



In [11]:
#triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

M=array([[1,2,3],[1,2,3],[1,2,3]])
print(M)

#lower triangular matrix
lower=tril(M)
print(lower)

#upper triangularr matrix
upper=triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


**Diagonal matrix**

All elements except the diagonal are zero.The diagonal can take different values.

In [12]:
#diagonal martix
from numpy import array
from numpy import diag

M=array([[1,2,3],
         [1,2,3],
         [1,2,3]])
print(M)
#extract diagonal vector
d=diag(M)
print('d: ',d)
#create diagonal matrix from vector

D=diag(d)
print(D)

a=array([1,2,3,4,5,6])
A=diag(a)
print('A: ',A)


b=array([[12,23,4,45],
        [12,45,78,7],
        [54,65,98,54],
        [36,25,14,98]])
g=diag(b)
G=diag(g)
print(g)
print(G)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
d:  [1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
A:  [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
[12 45 98 98]
[[12  0  0  0]
 [ 0 45  0  0]
 [ 0  0 98  0]
 [ 0  0  0 98]]


**IDentity matrix**


In [13]:
#identity matrix
from numpy import identity
I=identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Orthogonal matrix**

Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1 then the vectors are called orthonormal because they are both orthogonal and normalized.
v . w = 0      or     v . w(transpose)=0

A matrix is orthogonal if its transpose is equal to its inverse.

In [14]:
#orthogonal matrix
from numpy.linalg import inv
Q=array([[1,0],
         [0,-1]])
print(Q)
#inverse equivalence
V=inv(Q)
print(Q.T)
print(V)

#identity equivalence
I=Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


Note, sometimes a number close to zero can be represented as -0 due to the rounding of floating point precision. Just take it as 0.0. Orthogonal matrices are useful tools as they are
computationally cheap and stable to calculate their inverse as simply their transpose.

# **MATRIX OPERATIONS**


> Transpose

> Inverse

> Trace

> Determinant

> Rank











In [ ]:
#Transpose matrix C=A^T
from numpy import array
A=array([[1,2],
         [3,4],
         [5,6]])
print(A)

#calculate transpose
C=A.T
print(C)

In [ ]:
#Inv () işlevi kullanılarak NumPy'da bir matris ters çevrilebilir

from numpy.linalg import inv
A=array([[1.0,2.0],
         [3.0,4.0]])
print(A)
B=inv(A)
print(B)
#multiply A and B
I=A.dot(B)
print(I)

Note, your specific results may vary given differences in  floating point precision on different hardware and software versions. Matrix inversion is used as an operation in solving systems of equations framed as matrix equations where we are interested in finding vectors of unknowns.
A good example is in finding the vector of coeficient values in linear regression.

In [15]:
#matrix trace
from numpy import trace
A=array([[1,2,3],
         [4,5,6],
         [7,8,9]])
print(A)
#calculate trace
B=trace(A)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


**Determinant**

In [16]:
#matrix determinant
from numpy import array
from numpy.linalg import det

A=array([
         [1,2,3],
         [4,5,6],
         [7,8,9]])
print(A)
#calculate determinant
B=det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


**Rank**

Vektörlerin oluşturduğu boyutların sayısını ifade eder.Örneğin, 0 rankı tüm vektörlerin bir noktaya yayıldığını gösterirken rank= 1 için tüm vektörler bir doğruya yayılır.Rank=2 tüm vektörlerin iki boyutlu bir düzlemde yer aldığını gösterir.

In [17]:
#vector rank
from numpy import array
from numpy.linalg import matrix_rank

#rank
v1=array([1,2,3])
print(v1)
rank1=matrix_rank(v1)
print(rank1)

#zero rank
v2=array([0,0,0,0,0])
print(v2)
rank2=matrix_rank(v2)
print(rank2)

[1 2 3]
1
[0 0 0 0 0]
0


In [18]:
#matrix rank
from numpy import array
from numpy.linalg import matrix_rank
#rank0
M0=array([[0,0],
          [0,0]])
print(M0)
R0=matrix_rank(M0)
print('R0: ',R0)

#rank1
M1=array([[1,2],
          [1,2]])
print(M1)
R1=matrix_rank(M1)
print('R1: ',R1)


#rank2
M2=array([[1,2],
          [3,4]])
print(M2)
R2=matrix_rank(M2)
print('R2: ',R2)

[[0 0]
 [0 0]]
R0:  0
[[1 2]
 [1 2]]
R1:  1
[[1 2]
 [3 4]]
R2:  2


**Sparse matrix**

A matrix is sparse if many of its coeficients are zero. The interest in sparsity arises
because its exploitation can lead to enormous computational savings and because
many large matrix problems that occur in practice are sparse.
| Page 1, Direct Methods for Sparse Matrices, Second Edition, 2017

sparsity=1-count of non-zero elements/total elements
The example has 13 zero values of the 18 elements in the matrix, giving this matrix a sparsity
score of 0.722 or about 72%.

In [19]:
#sparse matrix
from numpy import array
from scipy.sparse import csr_matrix
#create dense matrix
A=array([
         [1,0,0,1,0,0],
         [0,0,2,0,0,1],
         [0,0,0,2,0,0]
])
print(A)

#convert to sparse matrix(CSR method)
S=csr_matrix(A)
print(S)

#reconstruct dense matrix
B=S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


sparsity = 1.0 - count_nonzero (A) / A.size

In [ ]:
#sparsity calculation
from numpy import array
from numpy import count_nonzero
#create dense matrix
A=array([
         [1,0,0,1,0,0],
         [0,0,2,0,0,1],
         [0,0,0,2,0,0]
])
print(A)
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)