In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


# Index, Slice and Reshape NumPy Arrays

In [2]:
#one-dimensional array
from numpy import array
#list of data
data=[11,22,33,44,55]
#array of data
data=array(data)
print(data)
print(type(data))
data2=[[11, 22],[33, 44],[55, 66]]
data=array(data)
print(data2)
print(type(data2))

[11 22 33 44 55]
<class 'numpy.ndarray'>
[[11, 22], [33, 44], [55, 66]]
<class 'list'>


In [3]:
#index a one dimensional array
from numpy import array
#define array
data=array([11, 22,33,44,55])
#index data
print(data[0])

#negative array indexing
print(data[-1])
print(data[-5])
#two dimensional indexing
data0=array([[11,22],[33,44],[55,66]])
print(data0[0,0])
print(data0[2,1])
#İlk satırdaki tüm öğelerle ilgileniyorsak:
print(data0[0,])

11
55
11
11
66
[11 22]


In [4]:
#slice a one-dimensional array
from numpy import array
data=array([11,22,33,44,55,66])
#Bir dizi boyutundaki tüm verilere, `: 'ile  erişebiliriz.
print(data[:])
#veya n. elemandan m.elemana n:m ile ulaşabiliriz.
print(data[0:3])
#sondaki m elemana erişmek için -m:0  kullanılır
print(data[-2:])

[11 22 33 44 55 66]
[11 22 33]
[55 66]


In [5]:
#Slicing the input/output variables
#X=[:,:-1] taking all rows (:) but keeping the last column
#y[:,-1]  taking all rows (:) but just last column

from numpy import array
data=array([[11,22,33],[44,55,66],[77,88,99]])
X,y=data[:,:-1],data[:,-1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


**spilt train and test rows**

In [6]:
#Example of slicing a train set from a dataset:
train=data[:split,:]
#Example of slicing a test set from a dataset.
test=data[split:,:]

NameError: ignored

In [7]:
data=array([[11,22,33],
           [44,55,66],
           [77,88,99]])
#seperate data
# The training dataset would be all rows from the beginning to the split point.
split=2
train,test=data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


**data shape**

In [9]:
#shape of one-dimensional array
from numpy import array
data=array([11,22,33,44,55])
print(data.shape)
#Running the example prints a tuple for the one dimension.

#shape of a two-dimensional array
from numpy import array
data=[[11,22],
      [33,44],
      [55,66]]
data=array(data)
print(data.shape)

#row and column shape of two-dimensional array
data=[[11,22],
      [33,44],
      [55,66]]
data=array(data)
print('Rows: %d' %data.shape[0])
print('Cols: %d' % data.shape[1])

(5,)
(3, 2)
Rows: 3
Cols: 2


In [10]:
#reshape 1D array to 2D
from numpy import array
data=array([11,22,33,44,55,66])
print(data.shape)
data=data.reshape((data.shape[0],1))
print(data.shape)
print(data)
#6 rows and 1 column

(6,)
(6, 1)
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]]
