<a href="https://colab.research.google.com/github/kardelenME/Data-Science/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import tensorflow as tf
import  numpy as np

In [4]:
#skaler bir nokta belirtir.(Vektörler yayılım göstermezler(rank=1 için doğruya yayılırlar.rank=2 için düzlemde yer alırlar)
rank_0_tensor=tf.constant(4)
print(rank_0_tensor)


tf.Tensor(4, shape=(), dtype=int32)


In [5]:
rank_1_tensor=tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

rank_2_tensor=tf.constant([[1,2],
                          [3,4],
                          [5,6]] ,dtype=tf.float16)

rank_3_tensor=tf.constant([
                           [[0,1,2,3,4],
                            [5,6,7,8,9]],
                           [[10,11,12,13,14],
                            [15,16,17,18,19]],
                           [[20,21,22,23,24],
                            [25,26,27,28,29]]],dtype=tf.float16)
print(rank_3_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]], shape=(3, 2, 5), dtype=float16)


In [6]:
#tensörü numpya dönüştürebiliriz
import numpy as np

np.array(rank_2_tensor)
rank_2_tensor.numpy()


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

tensörler float integerın dışında kompleks sayılar ve string gibi başka türleri de içerir.

## **Basic math on tensors**

In [7]:
a=tf.constant([[1,2],
               [3,4]])
b = tf.constant([[1, 1],
                 [1, 1]])
print(tf.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))



tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


**Note**
def matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
Multiplies matrix a by matrix b, producing a * b.
If one or both of the matrices contain a lot of zeros, a more efficient multiplication algorithm can be used by setting the corresponding a_is_sparse or b_is_sparse flag to True. These are False by default. This optimization is only available for plain matrices (rank-2 tensors) with datatypes bfloat16 or float32.
Tensor with same type and rank as a. transpose_a: If True, a is transposed before multiplication. transpose_b: If True, b is transposed before multiplication. adjoint_a: If True, a is conjugated and transposed before multiplication. adjoint_b: If True, b is conjugated and transposed before multiplication. a_is_sparse: If True, a is treated as a sparse matrix. Notice, this **does not support tf.sparse.SparseTensor**, it just makes optimizations that assume most values in a are zero. See tf.sparse.sparse_dense_matmul for some support for tf.sparse.SparseTensor multiplication. b_is_sparse: If True, b is treated as a sparse matrix. Notice, this **does not support tf.sparse.SparseTensor**, it just makes optimizations that assume most values in a are zero. See tf.sparse.sparse_dense_matmul for some support for tf.sparse.SparseTensor multiplication. name: Name for the operation (optional).

In [8]:
#matmul is matrix multiplication, not element-wise multiplication

print(a+b) #element-wise add
print(a*b) #element-wise multiplication
print(a@b) #matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


Tensors are used in all kinds of operations (ops).

In [9]:
c=tf.constant([[4.0,5.0],[10.0,1.0]])

#find the largest value
print(tf.reduce_max(c))
#find the index of the largest value
print(tf.argmax(c))
#compute the softmax 
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)




*   Shape:tensörün her bir boyutunun uzunluğu
*   Rank:Boyut sayısı.Skaler için rank=0.vektör için rank=1 matris için rank=2
*   Axis or dimension:tensörün boyutu
*   Size:Tensördeki toplam öğe sayısı






**Note ??**
Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

In [10]:
rank_4_tensor=tf.zeros([3,2,4,5])


axis 0->3->batch

axis 1->2->width

axis 2->4->height

axis -1->5->features

In [11]:
print("type of every element:", rank_4_tensor.dtype)
print("number of axes:", rank_4_tensor.ndim) #returns the Number of tensor DIMensions
print("shape of tensor:", rank_4_tensor.shape)
print("elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("total number of elements(3*2*4*5):", tf.size(rank_4_tensor).numpy())

type of every element: <dtype: 'float32'>
number of axes: 4
shape of tensor: (3, 2, 4, 5)
elements along axis 0 of tensor: 3
elements along the last axis of tensor: 5
total number of elements(3*2*4*5): 120


## **Indexing**
### Single-axis indexing
TensorFlow follows standard Python indexing rules

indexes start at 0

negative indices count backwards from the end

colons, :, are used for slices: start:stop:step

In [12]:
rank_1_tensor=tf.constant([0,1,2,3,4,5,6,7])
print(rank_1_tensor.numpy())
print("second:", rank_1_tensor[1].numpy())
print("last:",rank_1_tensor[-1].numpy())

[0 1 2 3 4 5 6 7]
second: 1
last: 7


In [13]:
print("everything:",rank_1_tensor[:].numpy())
print("before 4:",rank_1_tensor[:4].numpy())
print("from 4 to the end",rank_1_tensor[4:].numpy())
print("from 2,before 7",rank_1_tensor[2:7].numpy())
print("every other item",rank_1_tensor[::2].numpy())
print("reversed",rank_1_tensor[::-1].numpy())

everything: [0 1 2 3 4 5 6 7]
before 4: [0 1 2 3]
from 4 to the end [4 5 6 7]
from 2,before 7 [2 3 4 5 6]
every other item [0 2 4 6]
reversed [7 6 5 4 3 2 1 0]


### Multi-axis indexing

Kurallar her eksen için bağımsız olarak geçerlidir.

In [14]:
print(rank_2_tensor.numpy())
print(rank_2_tensor[1,-2].numpy())

#get row and column tensors
print("second row:",rank_2_tensor[1,:].numpy())
print("second column:",rank_2_tensor[:,1].numpy())
print("last row:",rank_2_tensor[-1,:].numpy())
print("first item in last column:",rank_2_tensor[0,-1].numpy())
print("skip the first row:",rank_2_tensor[1:,:].numpy())




[[1. 2.]
 [3. 4.]
 [5. 6.]]
3.0
second row: [3. 4.]
second column: [2. 4. 6.]
last row: [5. 6.]
first item in last column: 2.0
skip the first row: [[3. 4.]
 [5. 6.]]


In [15]:
#her örneğin son özelliğini seçme
print(rank_3_tensor[:,:,4])

tf.Tensor(
[[ 4.  9.]
 [14. 19.]
 [24. 29.]], shape=(3, 2), dtype=float16)


###Manipulating Shapes


In [19]:
x=tf.constant([[1],[2],[3]])
print(x.shape)

print(x.shape.as_list())

reshaped=tf.reshape(x,[1,3])
print(x.shape)
print(reshaped.shape)

(3, 1)
[3, 1]
(3, 1)
(1, 3)


In [21]:
print(rank_3_tensor)
#bir tensörü düzleştirirseniz,hafızaya hangi sırayla yerleştirildiğini görebilirsiniz:
print(tf.reshape(rank_3_tensor,[-1]))


tf.Tensor(
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]], shape=(3, 2, 5), dtype=float16)
tf.Tensor(
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.], shape=(30,), dtype=float16)


In [24]:
#ancak dilimlerin karışmaması için (3x2)x5 veya 3x(2x5) olarak yeniden şekillendirmek daha mantıklıdır:
print(tf.reshape(rank_3_tensor,[3*2,5]))
print(tf.reshape(rank_3_tensor,[3,2*5]))# veya [3,-1] şeklinde ifade edilebilir.
#rasgele uygun sayılarla farklı reshapeler yapmak mümkün ama anlamsız bir eksen sıralaması işimize yaramaz:
print(tf.reshape(rank_3_tensor,[5,6]))

tf.Tensor(
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]], shape=(6, 5), dtype=float16)
tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]], shape=(3, 10), dtype=float16)
tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]], shape=(5, 6), dtype=float16)


## **Broadcasting**

Broadcasting, Numpy'daki equivalent feature dan gelir.
Daha küçük dizi, uyumlu şekillere sahip olmaları için daha büyük dizi boyunca "broadcast edilir/yayınlanır".Broadcast, dizi işlemlerini vektörleştirmenin bir yolunu sağlar, böylece döngü Python yerine C'de gerçekleşir. Bunu gereksiz veri kopyaları yapmadan yapar ve genellikle verimli algoritma uygulamalarına yol açar. Bilgisayarı yavaşlatan belleğin verimsiz kullanımına yol açtığı için yayın yapmanın kötü bir fikir olduğu durumlar da vardır.Bu konu sonra detaylandırılacaktır.


In [26]:
x=tf.constant([1,2,3])
y=tf.constant(2)
z=tf.constant([2,2,2])
#All of these are the same computation
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [28]:
#these are the same computations
x=tf.reshape(x,[3,1])
y=tf.range(1,5)
print(x)
print(y)
print(tf.multiply(x,y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [29]:
#same operation without broadcasting
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


## **Ragged Tensor**

In [30]:
ragged_list= [
              [0,1,2,3],
              [4,5],
              [6,7,8],
              [9]]

In [32]:
ragged_tensor=tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


##**String Tensors** 

In [33]:
#tensor can be strings:
scalar_string_tensor=tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [35]:
tensor_of_strings=tf.constant(["Gray wolf",
                               "Quick brown fox",
                               "Lazy dog"])
#shape ettiğimizde sadece verinin boyutlarını alırız stringlerin uzunluğunu değil.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


string tensorü split metoduyla parçalayabiliriz ve her kelimeyi ayırabiliriz ancak her bir string cümle eşit sayıda kelime düzeninde değilse ragged tensörü elde ederiz.

In [36]:
print(tf.strings.split(scalar_string_tensor,sep=" "))
print(tf.strings.split(tensor_of_strings))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [ ]:
text=tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text," ")))

##**Sparse Tensor**

In [37]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
